package com.liveperson.api.${entityNameLowerCase};



/**
 * autogenerated as part of archetype
 */

 public class ${entityClassName} {

    public static void main(String[] args) {
            System.out.println("Hello, World");
    }
}


